"""Backup & Restore routes - ZIP download/upload of all MongoDB collections."""
from fastapi import APIRouter, UploadFile, File, HTTPException
from fastapi.responses import StreamingResponse
from database import db
from datetime import datetime, timezone
from bson import ObjectId
import json
import io
import zipfile

router = APIRouter()

# Collections to backup (all app data)
BACKUP_COLLECTIONS = [
    "agent_payments", "bank_accounts", "branding", "byproduct_sales",
    "cash_transactions", "dc_deliveries", "dc_entries", "diesel_accounts",
    "diesel_pumps", "frk_purchases", "fy_settings", "gst_opening_balances",
    "gunny_bags", "hemali_items", "hemali_payments", "local_party_accounts",
    "mandi_targets", "mill_entries", "mill_parts", "mill_parts_stock",
    "milling_entries", "msp_payments", "opening_balances", "opening_stock",
    "private_paddy", "private_payments", "purchase_vouchers", "rice_sales",
    "sale_vouchers", "settings", "staff", "staff_advance", "staff_attendance",
    "staff_payments", "store_rooms", "truck_lease_payments", "truck_leases",
    "truck_owner_payments", "truck_payments", "users"
]


class BackupEncoder(json.JSONEncoder):
    """Handle ObjectId and datetime serialization."""
    def default(self, obj):
        if isinstance(obj, ObjectId):
            return str(obj)
        if isinstance(obj, datetime):
            return obj.isoformat()
        return super().default(obj)


@router.get("/backup/download")
async def download_backup(username: str = "", role: str = ""):
    """Download all data as a ZIP file containing JSON files per collection."""
    if role != "admin":
        raise HTTPException(status_code=403, detail="Sirf Admin backup download kar sakta hai")

    zip_buffer = io.BytesIO()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        meta = {
            "backup_date": datetime.now(timezone.utc).isoformat(),
            "version": "50.1.0",
            "collections": [],
            "created_by": username
        }

        for coll_name in BACKUP_COLLECTIONS:
            docs = []
            async for doc in db[coll_name].find({}):
                docs.append(doc)

            if docs:
                json_data = json.dumps(docs, cls=BackupEncoder, ensure_ascii=False, indent=2)
                zf.writestr(f"{coll_name}.json", json_data)
                meta["collections"].append({"name": coll_name, "count": len(docs)})

        zf.writestr("_backup_meta.json", json.dumps(meta, indent=2))

    zip_buffer.seek(0)
    filename = f"mill_backup_{timestamp}.zip"

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@router.post("/backup/restore")
async def restore_backup(username: str = "", role: str = "", file: UploadFile = File(...)):
    """Restore data from a backup ZIP file. Replaces existing data."""
    if role != "admin":
        raise HTTPException(status_code=403, detail="Sirf Admin backup restore kar sakta hai")

    if not file.filename.endswith('.zip'):
        raise HTTPException(status_code=400, detail="Sirf ZIP file upload karein")

    content = await file.read()
    if len(content) > 100 * 1024 * 1024:  # 100MB limit
        raise HTTPException(status_code=400, detail="File size 100MB se zyada hai")

    try:
        zf = zipfile.ZipFile(io.BytesIO(content))
    except zipfile.BadZipFile:
        raise HTTPException(status_code=400, detail="Invalid ZIP file")

    # Validate backup meta
    if "_backup_meta.json" not in zf.namelist():
        raise HTTPException(status_code=400, detail="Ye valid backup file nahi hai (_backup_meta.json missing)")

    meta = json.loads(zf.read("_backup_meta.json"))
    restored = []
    skipped = []

    for name in zf.namelist():
        if name == "_backup_meta.json" or not name.endswith('.json'):
            continue

        coll_name = name.replace('.json', '')
        if coll_name not in BACKUP_COLLECTIONS:
            skipped.append(coll_name)
            continue

        try:
            docs = json.loads(zf.read(name))
            if not isinstance(docs, list) or len(docs) == 0:
                skipped.append(coll_name)
                continue

            # Clean _id fields (will be regenerated by MongoDB)
            for doc in docs:
                if '_id' in doc:
                    del doc['_id']

            # Clear existing and insert backup data
            await db[coll_name].delete_many({})
            await db[coll_name].insert_many(docs)
            restored.append({"name": coll_name, "count": len(docs)})
        except Exception as e:
            skipped.append(f"{coll_name} (error: {str(e)})")

    return {
        "success": True,
        "message": f"Backup restore ho gaya! {len(restored)} collections restored.",
        "backup_date": meta.get("backup_date", "unknown"),
        "restored": restored,
        "skipped": skipped
    }
