"""
Iteration 136: Test PDF slip layout and WhatsApp toggle persistence
- PDF slip should have 2 copies (PARTY COPY + CUSTOMER COPY) with cut line
- WhatsApp toggle should persist enabled=false and enabled=true correctly
"""
import pytest
import requests
import os

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')

class TestWhatsAppTogglePersistence:
    """Test WhatsApp enabled toggle saves and retrieves correctly"""
    
    def test_whatsapp_toggle_off(self):
        """PUT enabled=false should persist and GET should return enabled=false"""
        # PUT with enabled=false
        put_response = requests.put(
            f"{BASE_URL}/api/whatsapp/settings",
            json={"enabled": False}
        )
        assert put_response.status_code == 200
        assert put_response.json().get("success") == True
        
        # GET should return enabled=false
        get_response = requests.get(f"{BASE_URL}/api/whatsapp/settings")
        assert get_response.status_code == 200
        data = get_response.json()
        assert data.get("enabled") == False, f"Expected enabled=False, got {data.get('enabled')}"
    
    def test_whatsapp_toggle_on(self):
        """PUT enabled=true should persist and GET should return enabled=true"""
        # PUT with enabled=true
        put_response = requests.put(
            f"{BASE_URL}/api/whatsapp/settings",
            json={"enabled": True}
        )
        assert put_response.status_code == 200
        assert put_response.json().get("success") == True
        
        # GET should return enabled=true
        get_response = requests.get(f"{BASE_URL}/api/whatsapp/settings")
        assert get_response.status_code == 200
        data = get_response.json()
        assert data.get("enabled") == True, f"Expected enabled=True, got {data.get('enabled')}"
    
    def test_whatsapp_toggle_off_without_api_key(self):
        """Toggle OFF should work even without API key"""
        # First set to ON
        requests.put(f"{BASE_URL}/api/whatsapp/settings", json={"enabled": True, "api_key": ""})
        
        # Now toggle OFF
        put_response = requests.put(
            f"{BASE_URL}/api/whatsapp/settings",
            json={"enabled": False, "api_key": ""}
        )
        assert put_response.status_code == 200
        
        # Verify it's OFF
        get_response = requests.get(f"{BASE_URL}/api/whatsapp/settings")
        assert get_response.json().get("enabled") == False


class TestPDFSlipGeneration:
    """Test PDF slip generation with proper layout"""
    
    # Test entry IDs from the problem statement
    ENTRY_ID_WITH_CASH_DIESEL = "782d2b15-d344-40c8-b57c-a9a0b66c649f"  # RST#4 with cash+diesel
    ENTRY_ID_RST3 = "b95fcf44-a0d8-44b2-afc8-ffa2eb111a9d"  # RST#3
    
    def test_pdf_slip_returns_valid_pdf(self):
        """GET /api/vehicle-weight/{id}/slip-pdf should return valid PDF"""
        response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/{self.ENTRY_ID_WITH_CASH_DIESEL}/slip-pdf"
        )
        assert response.status_code == 200
        assert response.headers.get("content-type") == "application/pdf"
        
        # Check PDF magic bytes
        content = response.content
        assert content[:4] == b'%PDF', "Response should start with PDF magic bytes"
        assert b'%%EOF' in content, "PDF should contain EOF marker"
    
    def test_pdf_full_slip_larger_than_party_only(self):
        """Full slip (2 copies) should be larger than party_only (1 copy)"""
        # Get full slip (2 copies)
        full_response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/{self.ENTRY_ID_WITH_CASH_DIESEL}/slip-pdf"
        )
        assert full_response.status_code == 200
        full_size = len(full_response.content)
        
        # Get party_only slip (1 copy)
        party_response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/{self.ENTRY_ID_WITH_CASH_DIESEL}/slip-pdf?party_only=1"
        )
        assert party_response.status_code == 200
        party_size = len(party_response.content)
        
        # Full slip should be larger (has 2 copies + cut line)
        assert full_size > party_size, f"Full slip ({full_size} bytes) should be larger than party_only ({party_size} bytes)"
    
    def test_pdf_slip_uses_reportlab(self):
        """PDF should be generated using ReportLab library"""
        response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/{self.ENTRY_ID_WITH_CASH_DIESEL}/slip-pdf"
        )
        assert response.status_code == 200
        content = response.content
        
        # ReportLab adds its signature to PDF
        assert b'ReportLab' in content, "PDF should be generated by ReportLab"
    
    def test_pdf_slip_uses_helvetica_fonts(self):
        """PDF should use Helvetica fonts"""
        response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/{self.ENTRY_ID_WITH_CASH_DIESEL}/slip-pdf"
        )
        assert response.status_code == 200
        content = response.content
        
        # Check for Helvetica font references
        assert b'Helvetica' in content, "PDF should use Helvetica font"
        assert b'Helvetica-Bold' in content, "PDF should use Helvetica-Bold font"
    
    def test_pdf_slip_party_only_returns_valid_pdf(self):
        """GET with party_only=1 should return valid PDF"""
        response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/{self.ENTRY_ID_WITH_CASH_DIESEL}/slip-pdf?party_only=1"
        )
        assert response.status_code == 200
        assert response.headers.get("content-type") == "application/pdf"
        content = response.content
        assert content[:4] == b'%PDF', "Response should start with PDF magic bytes"
    
    def test_pdf_slip_404_for_invalid_id(self):
        """GET with invalid ID should return 404"""
        response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/invalid-id-12345/slip-pdf"
        )
        assert response.status_code == 404
    
    def test_pdf_slip_rst3_entry(self):
        """Test PDF generation for RST#3 entry"""
        response = requests.get(
            f"{BASE_URL}/api/vehicle-weight/{self.ENTRY_ID_RST3}/slip-pdf"
        )
        assert response.status_code == 200
        assert response.headers.get("content-type") == "application/pdf"
        content = response.content
        assert b'%PDF' in content[:10]


class TestVehicleWeightAPI:
    """Basic vehicle weight API tests"""
    
    def test_list_vehicle_weights(self):
        """GET /api/vehicle-weight should return list of entries"""
        response = requests.get(f"{BASE_URL}/api/vehicle-weight")
        assert response.status_code == 200
        data = response.json()
        assert "entries" in data
        assert "count" in data
        assert isinstance(data["entries"], list)
    
    def test_get_pending_vehicles(self):
        """GET /api/vehicle-weight/pending should return pending list"""
        response = requests.get(f"{BASE_URL}/api/vehicle-weight/pending")
        assert response.status_code == 200
        data = response.json()
        # Response is dict with 'pending' key containing list
        assert "pending" in data or isinstance(data, list), "Response should have pending list"
        if isinstance(data, dict):
            assert isinstance(data.get("pending", []), list)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
