/**
 * Offline Activation File (.mlic) — Verify + Import
 *
 * Flow on desktop side:
 *   1. User clicks "Import Offline File" in activation UI
 *   2. Electron opens file-dialog → selects .mlic (plain JSON)
 *   3. This module verifies Ed25519 signature using the embedded public key
 *      (or one fetched from central server on first online visit).
 *   4. If valid + license active + not expired → creates local license cache
 *      bound to current machine fingerprint.
 *   5. Optional: if machine has internet, also pings central server's
 *      /api/license/activate-mlic so the server records the binding.
 */
const fs = require('fs');
const crypto = require('crypto');
const { app } = require('electron');
const path = require('path');
const os = require('os');

// ====== EMBEDDED PUBLIC KEY ======
// This key is baked into the installer at build time by scripts/update-public-key.js.
// The desktop app will verify .mlic files offline using this key. If empty/invalid,
// fallback: fetch once online from GET /api/license/public-key and cache locally.
//
// Generated by: node scripts/fetch-public-key.js (pulls from central server).
//
const EMBEDDED_PUBLIC_KEY = process.env.MLIC_PUBLIC_KEY_OVERRIDE || '';

const PUB_KEY_CACHE_FILE = 'mlic-public-key.pem';

function getPubKeyCachePath() {
  try { return path.join(app.getPath('userData'), PUB_KEY_CACHE_FILE); }
  catch { return path.join(os.homedir(), '.millentry-' + PUB_KEY_CACHE_FILE); }
}

function loadCachedPublicKey() {
  try {
    const p = getPubKeyCachePath();
    if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8');
  } catch {}
  return null;
}

function saveCachedPublicKey(pem) {
  try { fs.writeFileSync(getPubKeyCachePath(), pem, 'utf8'); } catch {}
}

/** Resolve the public key — embedded first, then cached fallback. */
function resolvePublicKey() {
  if (EMBEDDED_PUBLIC_KEY && EMBEDDED_PUBLIC_KEY.includes('BEGIN PUBLIC KEY')) return EMBEDDED_PUBLIC_KEY;
  const cached = loadCachedPublicKey();
  if (cached && cached.includes('BEGIN PUBLIC KEY')) return cached;
  return null;
}

/** Fetch public key from central server once and cache it. Called by the activation UI on first use. */
async function fetchAndCachePublicKey(serverUrl) {
  const https = require('https');
  const http = require('http');
  return new Promise((resolve, reject) => {
    const url = new URL((serverUrl || '').replace(/\/+$/, '') + '/api/license/public-key');
    const lib = url.protocol === 'https:' ? https : http;
    const req = lib.request({
      method: 'GET', hostname: url.hostname, port: url.port || (url.protocol === 'https:' ? 443 : 80),
      path: url.pathname, timeout: 10000,
    }, (res) => {
      let chunks = '';
      res.on('data', c => chunks += c);
      res.on('end', () => {
        try {
          const j = JSON.parse(chunks);
          if (j && j.public_key && j.algorithm === 'ed25519') {
            saveCachedPublicKey(j.public_key);
            resolve(j.public_key);
          } else reject(new Error('Malformed public key response'));
        } catch (e) { reject(new Error('Failed to parse public key response')); }
      });
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(new Error('Timeout')); });
    req.end();
  });
}

// ====== Deterministic canonicalization (must match server's canonicalize()) ======
function sortKeys(v) {
  if (Array.isArray(v)) return v.map(sortKeys);
  if (v && typeof v === 'object') {
    const out = {};
    for (const k of Object.keys(v).sort()) out[k] = sortKeys(v[k]);
    return out;
  }
  return v;
}
function canonicalize(obj) { return JSON.stringify(sortKeys(obj)); }

/** Verify a payload's Ed25519 signature. Returns { valid, reason? }. */
function verifyMlicPayload(payload, publicKeyPem) {
  if (!payload || typeof payload !== 'object') return { valid: false, reason: 'Not a JSON object' };
  if (!payload.signature || payload.signature_alg !== 'ed25519') {
    return { valid: false, reason: 'Missing or unsupported signature' };
  }
  if (!publicKeyPem) return { valid: false, reason: 'No public key available — connect to internet once to fetch it' };
  try {
    const { signature, signature_alg, ...rest } = payload;
    const canonical = canonicalize(rest);
    const pub = crypto.createPublicKey(publicKeyPem);
    const sigBuf = Buffer.from(signature, 'base64');
    const ok = crypto.verify(null, Buffer.from(canonical, 'utf8'), pub, sigBuf);
    return ok ? { valid: true } : { valid: false, reason: 'Signature mismatch — file corrupted or forged' };
  } catch (e) {
    return { valid: false, reason: 'Verification error: ' + e.message };
  }
}

/** Sanity check after verify. */
function validateLicenseSemantics(payload) {
  const lic = payload.license;
  if (!lic || !lic.key) return { ok: false, reason: 'No license key in payload' };
  if (lic.expires_at) {
    const exp = new Date(lic.expires_at);
    if (isFinite(exp.getTime()) && exp.getTime() < Date.now()) {
      return { ok: false, reason: 'License has already expired on ' + exp.toISOString().slice(0, 10) };
    }
  }
  return { ok: true };
}

/**
 * Read a .mlic file from disk, verify, and return the payload.
 * No state change to the license cache — that's the caller's job.
 */
async function readAndVerifyMlicFile(filePath, serverUrl) {
  if (!fs.existsSync(filePath)) throw new Error('File not found');
  let raw;
  try { raw = fs.readFileSync(filePath, 'utf8'); }
  catch (e) { throw new Error('Cannot read file: ' + e.message); }
  let payload;
  try { payload = JSON.parse(raw); }
  catch { throw new Error('File is not valid JSON'); }
  let pub = resolvePublicKey();
  if (!pub && serverUrl) {
    // Try to fetch once — offline install with embedded key absent
    try { pub = await fetchAndCachePublicKey(serverUrl); } catch { /* ignore */ }
  }
  const v = verifyMlicPayload(payload, pub);
  if (!v.valid) throw new Error(v.reason);
  const s = validateLicenseSemantics(payload);
  if (!s.ok) throw new Error(s.reason);
  return payload;
}

module.exports = {
  readAndVerifyMlicFile,
  verifyMlicPayload,
  resolvePublicKey,
  fetchAndCachePublicKey,
  saveCachedPublicKey,
  loadCachedPublicKey,
  canonicalize,
};
